apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "aks-demo01-vault"
    objects: |
      array:
        - |
          objectName: aks-test-key
          objectType: secret
    tenantId: "6cb5ff9e-b980-4f06-8055-9f1f9f78ea98"
