apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
  namespace: sample-app
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "aks-demo01-vault"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "52d03af9-0195-4f8e-88f8-510e899395f2"
    objects: |
      array:
        - |
          objectName: aks-test-key
          objectType: secret
    tenantId: "970b20b6-4781-476f-8a3f-f630fa0566fc"
