apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-app
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: soumentrivedi/hello-world:v1
          env:
            - name: HELLO_WORLD_SECRET
              valueFrom:
                secretKeyRef:
                  name: aks-test-key
                  key: aks-test-key
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv"
            nodePublishSecretRef:
              name: secrets-store-creds
